export const LAY_DANH_SACH_BANNER = "LAY_DANH_SACH_BANNER";
export const LAY_DANH_SACH_PHIM = "LAY_DANH_SACH_PHIM";
export const LAY_THONG_TIN_PHIM = "LAY_THONG_TIN_PHIM";
export const SEARCH_PHIM = "SEARCH_PHIM";
